import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import BasicLayout from "@/components/Layouts/BasicLayout";

const Index: NextPage = () => {

  
  return (
    <>
      <Head>
        <title>websekai-nextjs</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <BasicLayout />
    </>
  );
};

export default Index;
